<a href="https://colab.research.google.com/github/bishwa79/bishwa79/blob/main/nlp_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# hi

In [ ]:
#hi

In [ ]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
corpus = ['I like eggs','I hate cats','I like eggs and I like cats']

In [ ]:
vectorizer = CountVectorizer(stop_words='english')

In [ ]:
x = vectorizer.fit_transform(corpus)

In [ ]:
x

<3x4 sparse matrix of type '<class 'numpy.int64'>'
	with 7 stored elements in Compressed Sparse Row format>

In [ ]:
print(x.toarray())

[[0 1 0 1]
 [1 0 1 0]
 [1 1 0 2]]


In [ ]:
vectorizer.get_feature_names_out()

array(['cats', 'eggs', 'hate', 'like'], dtype=object)

In [ ]:
import nltk

In [ ]:
from nltk.stem import PorterStemmer

In [ ]:
stemmer = PorterStemmer()

In [ ]:
sentence = 'going is criminal offense'.split()

In [ ]:
for token in sentence:
  print(stemmer.stem(token),end=', ')

go, is, crimin, offens, 

In [ ]:
from nltk.stem import WordNetLemmatizer

In [ ]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...


True

In [ ]:
from nltk.corpus import wordnet

In [ ]:
lemme = WordNetLemmatizer()

In [ ]:
for token in sentence:
  print(lemme.lemmatize(token,wordnet.VERB),end=' ')

go be criminal offense 

In [ ]:
import pandas as pd

In [ ]:
#tf = pd.read_csv('tmdb_5000_movies.csv')

FileNotFoundError: ignored

In [ ]:
tf.head()

In [ ]:
tf.shape

In [ ]:
tf.isnull().sum()

In [ ]:
tf = tf[['genres','keywords','overview','original_title']]

In [ ]:
tf.isnull().sum()

In [ ]:
tf.dropna()

In [ ]:
import pandas as pd

# Create a DataFrame
data = {'A': [1, 2, 3], 'B': [4, 5, 6]}
df = pd.DataFrame(data)

# Apply a function to each column
df = lambda x: x * 2


In [ ]:
import json

In [ ]:
x = tf.iloc[0]
x

In [ ]:
i= json.loads(x['genres'])
i

In [ ]:
a=[' '.join(''.join(ii['name'].split()) for ii in i)]
a

In [ ]:
def genres_change(row):
  df = json.loads(row['genres'])
  for j in df:
    b=[]
    b=b + [' '.join(''.join(ii['name'].split()) for ii in j)]
  print(b)

In [ ]:
import json

def genres_change(row):
    df = json.loads(row['genres'])
    result = [' '.join(''.join(ii['name'].split()) for ii in j) for j in df]
    return result

tf['strings'] = tf.apply(genres_change, axis=1)


In [ ]:
' '.join(''.join(jj['name'].split()) for jj in i)

In [ ]:
tf['strings'] = tf.apply(genres_change,axis=1)

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfid = TfidfVectorizer(max_features=2000)
X = tf['overview']
X = X.dropna()
X = tfid.fit_transform(X)
X


In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
scores = cosine_similarity(X[0],X)

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
scores.shape

In [ ]:
scores = scores.flatten()

In [ ]:
scores.shape

In [ ]:
plt.plot(scores)

In [ ]:
n,m = int(input().split(" "))
#n,m = v
print(n)
print(m)

In [ ]:
a=[3]
a = list(input())

In [ ]:
n,m = input().split()
arr=[n]
arr = list(input())
a=[m]
b=[m]
a = list(input())
b = list(input())
c=0
for i in arr:
    for j in a:
        if i==j:
            c=c+1
    for k in b:
        if i==k:
            c=c-1
print(c)

In [ ]:
import spacy
nlp = spacy.load("en_core_web_sm")

In [ ]:
text = "I am a boy.I like dogs"

In [ ]:
doc = nlp(text)

In [ ]:
print(doc.text)

I am a boy.I like dogs


In [ ]:
a=[list(token.text) for token in list(doc.sents)]

In [ ]:
a

[['I', ' ', 'a', 'm', ' ', 'a', ' ', 'b', 'o', 'y', '.'],
 ['I', ' ', 'l', 'i', 'k', 'e', ' ', 'd', 'o', 'g', 's']]

In [ ]:
for t in a:
  b=t.split()

In [ ]:
b

['I', 'like', 'dogs']

In [ ]:
doc = [[token.text for token in sentence if token.is_stop!=True and token.is_punct!=True] for sentence in doc.sents]

In [ ]:
doc

[['boy'], ['like', 'dogs']]

In [ ]:
print(list(doc.sents))

[I am a boy., I like dogs]


In [ ]:
print([token.text for token in doc if token.is_stop !=True and token.is_punct !=True])

['boy', 'like', 'dogs']


In [ ]:
print([(token, token.lemma_) for token in doc])

[(I, 'I'), (am, 'be'), (a, 'a'), (boy, 'boy'), (., '.'), (I, 'I'), (like, 'like'), (dogs, 'dog')]


In [ ]:
print([(token.text, token.lemma_) for token in doc])

[('I', 'I'), ('am', 'be'), ('a', 'a'), ('boy', 'boy'), ('.', '.'), ('I', 'I'), ('like', 'like'), ('dogs', 'dog')]


In [ ]:
from collections import Counter

In [ ]:
print(Counter(doc))

Counter({I: 1, am: 1, a: 1, boy: 1, .: 1, I: 1, like: 1, dogs: 1})


In [ ]:
print([(token,token.pos_)for token in doc])

[(I, 'PRON'), (am, 'AUX'), (a, 'DET'), (boy, 'NOUN'), (., 'PUNCT'), (I, 'PRON'), (like, 'VERB'), (dogs, 'NOUN')]


In [ ]:
doc = nlp("India is a very beautiful. Apple is a fruit")

In [ ]:
print([(token,token.label_)for token in doc.ents])

[(India, 'GPE'), (Apple, 'ORG')]
